[project]
name = "broadcaster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "apprise>=1.9.5",
    "nats-py>=2.12.0",
]
